### ISSUE TITLE
where can I find `native_adapters` package

### ISSUE THREAD

**Issue by JyotiLuxolis** [roncapat/ROS2-HAL-LucidLabs-Helios2#4]

**Comment by JyotiLuxolis** [comment]
Hello, `native_adapters` package is used for this repo. How can I install it? `rosdep` doesn't help

**Comment by roncapat** [comment]
Hi, thanks for your interest! Here you are: https://github.com/roncapat/ros2_native_adapters

BTW, native_adapters are not so well documented as far as now, but in brief, they allow to compose this node with other nodes (properly, rclcpp components), and if all subscribing components use type adaptation too, you have zero-copy message passing of point clouds from this component. This means you have very low latencies and native access to the PCL representation of the point cloud (pcl::PointCloud<PointT> type). 

In your subscriber, you can use native_adapters and write a proxy callback as follows:

```
void SubscribingComponent::callback_pointcloud(const std::shared_ptr<const StampedPointCloud2>& msg) {
  std::visit(
     [&, header=msg->header] (auto&& cloud) {
          this->process_message(header, cloud);
     }, 
     msg->cloud);
}
```

with 'process_message()' being a templated member where PointT type is left to the compiler to determine. This way, you support all kind of PCL point types you may receive through the adapter.

**Comment by roncapat** [comment]
See also https://ros.org/reps/rep-2007.html
I may provide an example package, if you want.

**Comment by roncapat** [comment]
I'm preparing here (https://github.com/roncapat/ros2-native-adapters-examples) an example. Please check tomorrow for full working example.

**Comment by roncapat** [comment]
@JyotiLuxolis now the test package works for me... if you want, give it a try! I'll leave the issue open until your feedback :)
